/**
 * Session-title helpers shared by the transcript task card and the subtask
 * dialog header.
 *
 * A subagent session is renamed on the server (the fork's plugin writes
 * `BETA: <generated name>`), and that name — not `subagent_type` — says what the
 * subtask is about. The live session title therefore wins and `subagent_type`
 * stays as the fallback: the card, its context-panel tab and the dialog header
 * all read this one value, so the surfaces cannot disagree.
 *
 * A freshly created session carries the server's `New session - <time>`
 * placeholder before the rename lands. The placeholder must lose to
 * `subagent_type`, or a surface would show a name that is not one and then
 * change back.
 */

import { formatSubagentTypeLabel } from './subagentTypeLabel';

const PLACEHOLDER_SESSION_TITLE_PREFIX = 'new session';

/** True for an unset title and for the server's autogenerated `New session` label. */
export const isPlaceholderSessionTitle = (title: unknown): boolean => {
    if (typeof title !== 'string') return true;
    const normalized = title.trim().toLowerCase();
    return normalized.length === 0 || normalized.startsWith(PLACEHOLDER_SESSION_TITLE_PREFIX);
};

/** The transcript card's title: live session title, else the agent type label. */
export const resolveTaskSessionTitle = (params: {
    sessionTitle?: string | null;
    subagentType?: unknown;
}): string => {
    const sessionTitle = params.sessionTitle;
    if (sessionTitle != null && !isPlaceholderSessionTitle(sessionTitle)) {
        return sessionTitle.trim();
    }
    return formatSubagentTypeLabel(params.subagentType);
};

/** Header title of the subtask dialog: live session title, else the label the card passes. */
export const resolveSubtaskSessionTitle = (params: {
    sessionTitle?: string | null;
    fallbackTitle: string;
}): string => {
    const sessionTitle = params.sessionTitle;
    if (sessionTitle != null && !isPlaceholderSessionTitle(sessionTitle)) {
        return sessionTitle.trim();
    }
    return params.fallbackTitle;
};
