import { describe, expect, test } from 'bun:test';

import { resolveSubtaskSessionTitle } from './sessionTitle';

const AGENT_LABEL = 'Explore';
const SESSION_TITLE = 'BETA: Разбор полей session.tokens (@explore subagent)';

describe('resolveSubtaskSessionTitle', () => {
  test('prefers the live session title over the tool part label', () => {
    expect(resolveSubtaskSessionTitle({ sessionTitle: SESSION_TITLE, fallbackTitle: AGENT_LABEL }))
      .toBe(SESSION_TITLE);
  });

  test('trims the live title before showing it', () => {
    expect(resolveSubtaskSessionTitle({ sessionTitle: `  ${SESSION_TITLE}  `, fallbackTitle: AGENT_LABEL }))
      .toBe(SESSION_TITLE);
  });

  test('falls back while the session is not loaded', () => {
    expect(resolveSubtaskSessionTitle({ sessionTitle: undefined, fallbackTitle: AGENT_LABEL }))
      .toBe(AGENT_LABEL);
    expect(resolveSubtaskSessionTitle({ sessionTitle: null, fallbackTitle: AGENT_LABEL }))
      .toBe(AGENT_LABEL);
  });

  test('falls back on a blank live title', () => {
    expect(resolveSubtaskSessionTitle({ sessionTitle: '', fallbackTitle: AGENT_LABEL })).toBe(AGENT_LABEL);
    expect(resolveSubtaskSessionTitle({ sessionTitle: '   ', fallbackTitle: AGENT_LABEL })).toBe(AGENT_LABEL);
  });

  test('ignores the autogenerated new-session placeholder', () => {
    expect(resolveSubtaskSessionTitle({ sessionTitle: 'New session', fallbackTitle: AGENT_LABEL }))
      .toBe(AGENT_LABEL);
    expect(resolveSubtaskSessionTitle({ sessionTitle: 'new session - 2026-02-14', fallbackTitle: AGENT_LABEL }))
      .toBe(AGENT_LABEL);
    expect(resolveSubtaskSessionTitle({ sessionTitle: '  NEW SESSION 17  ', fallbackTitle: AGENT_LABEL }))
      .toBe(AGENT_LABEL);
  });

  test('keeps a real title that only mentions a new session later', () => {
    const title = 'Follow-up: new session flow';
    expect(resolveSubtaskSessionTitle({ sessionTitle: title, fallbackTitle: AGENT_LABEL })).toBe(title);
  });
});
